apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nattawin/mynode:1.0.$BUILD_NUMBER
        ports:
        - containerPort: 8080
