apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    run: nodejs-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32109
    protocol: TCP
  selector:
    app: nodejs
